# Generated by Django 5.2 on 2025-04-29 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='debt',
            name='debt_amount_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='expense',
            name='expense_amount_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='split',
            name='split_share_gte_0',
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='debt_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='expense_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='split',
            constraint=models.CheckConstraint(condition=models.Q(('share__gte', 0)), name='split_share_gte_0'),
        ),
    ]
